#!/usr/bin/env bats

@test "flyway binary is installed" {
  run stat /opt/flyway/flyway
  [ "$status" -eq 0 ]
}

@test "flyway.conf is created" {
  run cat /opt/flyway/conf/flyway.conf
  [ "$status" -eq 0 ]
  [ "${lines[0]}" = "# This file was generated by Chef" ]
  [ "${lines[1]}" = "# Do NOT modify this file by hand." ]
  [ "${lines[2]}" = "#" ]
  [ "${lines[3]}" = "flyway.user=notset" ]
  [ "${lines[4]}" = "flyway.url=jdbc:mysql://notset/mysql" ]
  [ "${lines[5]}" = "flyway.schemas=flywaydb_test" ]
  [ "${lines[6]}" = "flyway.locations=filesystem:/tmp/db" ]
  [ "${lines[7]}" = "flyway.cleanDisabled=true" ]
  [ "${lines[8]}" = "flyway.placeholders.test_user=test" ]
}

@test "flyway_test.conf is created" {
  run cat /opt/flyway/conf/flyway_test.conf
  [ "$status" -eq 0 ]
  [ "${lines[0]}" = "# This file was generated by Chef" ]
  [ "${lines[1]}" = "# Do NOT modify this file by hand." ]
  [ "${lines[2]}" = "#" ]
  [ "${lines[3]}" = "flyway.user=root" ]
  [ "${lines[4]}" = "flyway.url=jdbc:mysql://localhost/mysql" ]
}
