#!/usr/bin/env bats

@test "flyway binary is installed" {
  run stat /opt/flyway/flyway
  [ "$status" -eq 0 ]
}

@test "default flyway config is created" {
  run cat /opt/flyway/conf/flyway.conf
  [ "$status" -eq 0 ]
  [ "${lines[0]}" = "# This file was generated by Chef" ]
  [ "${lines[1]}" = "# Do NOT modify this file by hand." ]
  [ "${lines[2]}" = "#" ]
  [ "${lines[3]}" = "flyway.url=jdbc:mysql://localhost/mysql" ]
  [ "${lines[4]}" = "flyway.schemas=flywaydb_test" ]
  [ "${lines[5]}" = "flyway.locations=filesystem:/tmp/db" ]
}
